name: Lint
on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup dependencies
        run: npm i -g markdownlint-cli prettier && npm i
      - name: Lint
        run: npm run lint:md
      - name: Prettier
        run: npm run prettier
